### PR TITLE
Update docs

### PR DESCRIPTION
**Pull request by victorfonsec4**
Update docs with usage on alerts and trigalerts

### CODE REVIEW

**Comment by kazhang** [comment]
Seems like github doesn't render the rst file properly, the commands are not wrapped inside code block

**Review by kazhang — COMMENTED** [review]
LGTM @rahul8590 ?

**Review by yoelcabo — APPROVED** [review]

**Comment by lexholden** [comment]
@victorfonsec4 @yoelcabo shall I merge this? Has been sitting here for ages.

**Comment by yoelcabo** [comment]
Definitely

**Pull request merged**
